package com.rentflow.notification.entity;

public enum NotificationType {
    DRIVER_VERIFICATION_EXPIRED,
    LISTING_REJECTED,
    PAYMENT_VOID_RETRY_REQUIRED,
    PAYMENT_VOID_RETRY_RESOLVED,
    PAYMENT_VOID_RETRY_FAILED_MAX_ATTEMPTS,
    SUPPORT_CASE_CREATED,
    SUPPORT_CASE_MESSAGE,
    SUPPORT_CASE_CLOSED,
    HOST_PAYOUT_CREATED,
    HOST_PAYOUT_UPDATED
}
